repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.6.4
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
      - id: pylint
        types: [python]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        stages: [push]
        pass_filenames: false
