# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Orodruin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Poetry Install
        run: |
          pip install poetry
          poetry install
      - name: isort Check
        run: poetry run isort . --check-only
      - name: Black Check
        run: poetry run black --check .
      - name: Pylint Check
        run: poetry run pylint orodruin tests
      - name: Mypy Check
        run: poetry run mypy orodruin
      - name: Test with pytest
        run: poetry run pytest
